#!/bin/bash
#PBS -N validation
#PBS -l select=1:ncpus=1:mem=4gb
#PBS -l walltime=24:00:00

echo "===== Job started at $(date '+%Y-%m-%d %H:%M:%S') ====="

source $HOME/WCTE_Production/config.sh

singularity exec -B "$HOME":"$HOME" \
             	-B "$MYLUSTRE":"$MYLUSTRE" \
              	"$IMAGE_SIM" \
             	bash -lc "source /opt/entrypoint.sh && \
               		root -l -b -q \"${MC_PRODUCTION}/validation/EventDisplay.c(\\\"${OUTPUT_PATH}/gamma/rootfiles/wcsim_wCDS_gamma_Uniform_0_1200MeV_*.root\\\")\""

singularity exec -B "$HOME":"$HOME" \
             	-B "$MYLUSTRE":"$MYLUSTRE" \
          	"$IMAGE_SIM" \
          	bash -lc "source /opt/entrypoint.sh && \
           		root -l -b -q \"${MC_PRODUCTION}/validation/VertexDistribution.c(\\\"${OUTPUT_PATH}/gamma/rootfiles/wcsim_wCDS_gamma_Uniform_0_1200MeV_*.root\\\")\""

singularity exec -B "$HOME":"$HOME" \
            	-B "$MYLUSTRE":"$MYLUSTRE" \
            	"$IMAGE_SIM" \
           	bash -lc "source /opt/WCSim/build/this_wcsim.sh && \
          	root -l -b -q \"${MC_PRODUCTION}/validation/EventDisplay_SingleEvent.c(\\\"${OUTPUT_PATH}/gamma/rootfiles/wcsim_wCDS_gamma_Uniform_0_1200MeV_*.root\\\", ${EVENT_ID})\""

echo "===== Job ended at $(date '+%Y-%m-%d %H:%M:%S') ====="
